### ISSUE TITLE
Asset containing `fc_chrXXXfYY_conv`

### ISSUE THREAD

**Issue by RabberDakk** [uyjulian/ed8pkg2glb#7]
I appreciate that your great helpful information. Let me ask you a question.

I read [this page](https://ghpages.uyjulian.pw/falcom-dumps/) `How do I get the high resolution face textures for Sen3, Sen4, and Hajimari?` then, I tried to extract the missing textures from the my purchased game data (ToCS IV + DCL), but I can't find any files like `fc_chrXXXfYY_conv`.

1. I applied `ed8pkg2glb` to `data/dlc/asset/D3D11/*pkg`, but these did not output. I digged at the source code, probably that `data/dlc/asset/D3D11/*pkg` does not seem to contain that textures.

2. I expected the highres texture is referenced from the main game's `data/asset/D3D11`, tried applying unpackpka and ed8pkg2glb to that assets, but could not find them. Similar data exists, but it is still different because the colors are wrong and the UVs do not match.

Could you tell me where I can extract high resolution face/hair textures like `fc_chrXXXfYY_conv`?

**Comment by uyjulian** [comment]
The relevant files are ones beginning with `FC_`.

There was a bug in earlier versions of the tool where certain files may not extract. This has been fixed.

**Comment by undefined90071** [comment]
tysm!

**Comment by RabberDakk** [comment]
tysm!!
