### ISSUE TITLE
dds to png conversion issue for non-square textures

### ISSUE THREAD

**Issue by hwjsnc** [uyjulian/ed8pkg2glb#8]
Example file: Trails into Reverie PC version, `I_KISIN_MENU.pkg` in assets.pka.

The right half of the resulting 1024x512 .png is blank. The left half consists of interleaved 4px stripes where half the stripes belong on the left and half should be on the right, with appropriate y offsets.

Without having looked at the code, I suspect the 4x4 pixel blocks are laid out in column-major order when they should be in row-major order (or perhaps the other way around).

**Comment by uyjulian** [comment]
Fixed in v0.4.1

Thanks!
